language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  matrix:
    - BUILD_SHARED=NO
      BUILD_TYPE=Coverage
    - BUILD_SHARED=NO
      BUILD_TYPE=Debug
    - BUILD_SHARED=NO
      BUILD_TYPE=Release
    - BUILD_SHARED=YES
      BUILD_TYPE=Coverage
    - BUILD_SHARED=YES
      BUILD_TYPE=Debug
    - BUILD_SHARED=YES
      BUILD_TYPE=Release

addons:
  apt:
    packages:
      - cmake
      - openssl
      - libssl-dev
    sources:
      - kubuntu-backports

before_install:
  - cmake --version

install:
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      PATH=~/.local/bin:${PATH};
      pip install --user --upgrade pip;
      pip install --user cpp-coveralls;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake
    -G "Unix Makefiles"
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED}
    "-DCMAKE_THIRD_PARTY_DIR=${HOME}/third-party"
    -DCMAKE_ENABLE_THIRD_PARTY_OUTPUT=YES
    ..

cache:
  directories:
    - $HOME/third-party

matrix:
  - fast_finish: true

script:
  - CTEST_OUTPUT_ON_FAILURE=1 make all test

after_success:
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      coveralls --include src --include include --gcov-options '\-lp' --root .. --build-root .;
    fi
